ServerRoot "/usr/local/apache2"
Listen 80
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule alias_module modules/mod_alias.so
LoadModule autoindex_module modules/mod_autoindex.so
User www-data
Group www-data
ServerAdmin ops@ambercell.lab
ServerName ambercell.lab
DocumentRoot "/usr/local/apache2/htdocs"
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined
TypesConfig conf/mime.types
AddType text/html .html
DirectoryIndex index.html

<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

Alias /portal/ "/usr/local/apache2/htdocs/portal/"
<Directory "/usr/local/apache2/htdocs/portal">
    Options Indexes
    Require all granted
</Directory>

Alias /uploads/ "/var/www/uploads/"
<Directory "/var/www/uploads">
    Options Indexes
    Require all granted
</Directory>

AliasMatch ^/wp-login\.php$ "/usr/local/apache2/htdocs/lure.txt"
AliasMatch ^/phpmyadmin/?$ "/usr/local/apache2/htdocs/lure.txt"
