worker_processes 1;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 256;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log /dev/stdout combined;
    sendfile on;
    keepalive_timeout 15;
    client_max_body_size 8m;
    server_tokens on;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /portal/ {
            alias /usr/share/nginx/html/portal/;
            autoindex on;
        }

        location /wp-login.php {
            return 200 'AmberCell lure — not WordPress';
            add_header Content-Type text/plain;
        }

        location /phpmyadmin/ {
            return 200 'AmberCell lure — not phpMyAdmin';
            add_header Content-Type text/plain;
        }

        location /uploads/ {
            alias /var/www/uploads/;
            client_body_temp_path /tmp/nginx-body;
            autoindex on;
        }
    }
}
