# AmberCell Dovecot — POP3 only, lure mailboxes.
protocols = pop3
listen = *

ssl = no
disable_plaintext_auth = no
auth_mechanisms = plain login

mail_location = mbox:~/mail:INBOX=/var/mail/%u
mail_privileged_group = mail
first_valid_uid = 100

passdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/users
}
userdb {
  driver = passwd
}

service pop3-login {
  chroot =
  inet_listener pop3 {
    port = 110
  }
}

service anvil {
  chroot =
}

log_path = /dev/stdout
info_log_path = /dev/stdout
debug_log_path = /dev/stdout
